modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Areas"
logoFile="icon.png"

[[mods]]
modId="areas"
version="5.7"
displayName="Areas"
displayURL="https://serilum.com/mod/areas"
authors="Rick South"
description='''Create custom named areas/towns with a radius using signs, which sends join and leave messages.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.areas]]
    modId="collective"
    mandatory=true
    versionRange="[7.54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.areas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"
